### ISSUE TITLE
setColor via json is not working

### ISSUE THREAD

**Issue by hoschult** [Joery-M/Govee-LAN-Control#4]
Hi,
I try to set color of my give led strip. Works fine with builtin color picker; However I stuck to inject a json color scheme to setColor node. I tried with:

![image](https://user-images.githubusercontent.com/20515558/210626542-36cc8f38-0f48-452b-8e89-b206ab731132.png)

However, it does not work. Can anybody share an example how to inject color via json to setColor node?

Thanks

**Comment by hoschult** [comment]
also tried something like this:

![image](https://user-images.githubusercontent.com/20515558/210626785-1ed197c1-1bd7-47f5-892e-e21c6a0b06a6.png)

but without luck.... Led strip turns off

**Comment by Joery-M** [comment]
Sorry for taking WAY too long to respond.

The value of `msg.payload` has to be one of these:

```json
{
  "rgb": [255, 255, 0]
}
```

```json
{
  "hex": "#000004"
}
```

```json
{
  "hsl": [100, 50, 100]
}
```

```json
{
  "kelvin": 4000
}
```

**Comment by hoschult** [comment]
thanks.

When feeding the the setColor node with

`{ "rgb": [ 128, 8, 54] }`

I got an node red crash

`2 Apr 17:13:53 - [red] Uncaught Exception:
2 Apr 17:13:53 - [error] TypeError: Cannot read properties of undefined (reading 'devicesArray')
    at setColorNode._inputCallback (/home/pi/.node-red/node_modules/govee-lan-control/dist/node-red/setColor.js:12:24)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at setColorNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at setColorNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at setColorNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:475:21)
`
