### ISSUE TITLE
Crashed node red when powering on give device

### ISSUE THREAD

**Issue by hoschult** [Joery-M/Govee-LAN-Control#8]
Hi. When using power on node, I do get the following error and node red stops:

```
Nov 11 17:08:39 raspimain Node-RED[434]: 11 Nov 17:08:39 - [red] Uncaught Exception:
Nov 11 17:08:39 raspimain Node-RED[434]: 11 Nov 17:08:39 - [error] TypeError: Cannot read properties of undefined (reading 'devicesArray')
Nov 11 17:08:39 raspimain Node-RED[434]:     at setPowerNode._inputCallback (/home/pi/.node-red/node_modules/govee-lan-control/dist/node-red/setPower.js:12:24)
Nov 11 17:08:39 raspimain Node-RED[434]:     at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
Nov 11 17:08:39 raspimain Node-RED[434]:     at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
Nov 11 17:08:39 raspimain Node-RED[434]:     at setPowerNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
Nov 11 17:08:39 raspimain Node-RED[434]:     at setPowerNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
Nov 11 17:08:39 raspimain Node-RED[434]:     at setPowerNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
Nov 11 17:08:39 raspimain Node-RED[434]:     at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
Nov 11 17:08:39 raspimain Node-RED[434]:     at processImmediate (node:internal/timers:478:21)
Nov 11 17:08:40 raspimain systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by drschnalli** [comment]
I get the same message does not matter if i use set color, power, brightness :(

**Comment by darthrater78** [comment]
Same. If I use a timestamp to trigger it crashes nodered with a " Service Node-RED exited with code 1 (by signal 0)"

If I try and use a boolean it crashes with " Service NGINX exited with code 0 (by signal 0)"
